name: Update files

on:
  schedule:
    - cron: '* 12 * * *'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Update files
        uses: MathieuSoysal/file-updater-for-release@v1.0.1
        with:
          files: README.md # List of files to update
          prefix: "io.github.me:javalib:" # Prefix before the version in your cas is io.github.me:javalib:

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.github_token }} # You need to create your own token with pull request rights
          commit-message: update readme
          title: Update readme
          body: Update readme to reflect release changes
          branch: update-readme
          base: main
