name: Update files

on:
  schedule:
    - cron: '* 11 * * *'
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-3d-contrib
    steps:
      - uses: actions/checkout@v3
      - uses: yoshi389111/github-profile-3d-contrib@0.7.1
        env:
          GITHUB_TOKEN: ${{ secrets.github_token }}
          USERNAME: ${{ JiuRanYa }}
      - name: Commit & Push
        run: |
          git config user.name JiuRanYa
          git config user.email 1084350607@qq.com
          git add -A .
          git commit -m "generate profile"
          git push
